### ISSUE TITLE
Circular import in AWS lambda

### ISSUE THREAD

**Issue by wellsoliver** [brianhelba/zipfile-deflate64#35]
I have a lambda in AWS in python 3.8 and in my `/lambda_function.py` file having this:

```
import zipfile
import zipfile_deflate64
```

Yields an error message of:

```
Unable to import module 'lambda_function': cannot import name 'deflate64' from partially initialized module 'zipfile_deflate64' (most likely due to a circular import) (/var/task/zipfile_deflate64/__init__.py)
```

Just wondering if you've heard of folks coming across this using AWS lambdas.

**Comment by rohannair11** [comment]
Hi, i'm using python 3.10, but facing the same issue as you. How did you fix this?

**Comment by wellsoliver** [comment]
Yes, essentially just using `zipfile_deflate64` and not `zipfile` -- I think (it's been a while) having both caused the conflict. Still just py 3.9 though, don't think it matters...

**Comment by rohannair11** [comment]
Did you make changes in the zipfile_deflate64 code itself? Since I tried removing the line containing "import zipfile" but the circular import issue still persists

**Comment by wellsoliver** [comment]
No. The current docker image we have is using 0.2.0 I think.
