### ISSUE TITLE
Example Windows Explorer Deflate64 zip file

### ISSUE THREAD

**Issue by madler** [brianhelba/zipfile-deflate64#39]
Can you provide a downloadable example of a zip file from Windows that uses Deflate64?

**Comment by brianhelba** [comment]
Sure, there's already a test file for this: https://github.com/brianhelba/zipfile-deflate64/blob/master/tests/data/deflate64.zip

**Comment by brianhelba** [comment]
Actually, I don't recall whether that file comes from Windows, or was generated by p7zip. Are you looking for something Windows-specific or just that it uses Deflate64?

**Comment by madler** [comment]
Indeed, I was looking for one made by Windows Explorer as you describe. Thanks!

**Comment by nhz2** [comment]
I created the following zip file on Windows Explorer to test the Julia package https://github.com/nhz2/CodecInflate64.jl 

[win11-deflate64.zip](https://github.com/user-attachments/files/16535555/win11-deflate64.zip)

Julia script used to generate the files:
```julia
using StableRNGs: StableRNG

# This script will create a "testdata" directory
# This directory can be compressed on windows to create
# a test for deflate64
# To compress, open the directory in File Explorer
# Then press ctrl A to select all the files.
# Next right click, and press "Compress to ZIP file" button.

rng = StableRNG(1234)

rm("testdata"; recursive=true, force=true)
dir = mkdir("testdata")

write(joinpath(dir,"abig.dat"), zeros(UInt8, 2^31))
for i in 0:500
    write(joinpath(dir,"small$(i).dat"), zeros(UInt8, i))
end

thing = rand(rng, UInt8, 200)
d = UInt8[]
for dist in [0:258; 1000:1030; 2000:1000:33000; 34000:10000:100_000]
    append!(d, thing)
    append!(d, rand(rng, 0x00:0x0f, dist))
end
write(joinpath(dir, "dist-rand.dat"), d)

for n in 65536-300:65536-100
    write(joinpath(dir, "dist-$(n).dat"), [thing; zeros(UInt8, n); thing])
end

write(joinpath(dir, "incomp.dat"), rand(rng, UInt8, 400_000))

# Finally write this file
write(joinpath(dir, "gen_files.jl"), read(@__FILE__))
```

**Comment by madler** [comment]
@nhz2 Thanks!
